hash-format = "sha256"

[[files]]
file = "config/alexsmobs.toml"
hash = "71bc9f77fc12e3eacc9b138fed9aa16bdce257514d3ad845599a60535ccf2434"

[[files]]
file = "config/backpacked.server.toml"
hash = "02eae75f965cb0d6ceb6395c5ab2eb0cdbdd51b8d5818900b1d8b6384a79f3ff"

[[files]]
file = "config/bcc-common.toml"
hash = "d41e36fbca9e8c6b1ce9a45408f0191d731d69bce2b7f80e480ca8517fa18b75"

[[files]]
file = "config/collective.json5"
hash = "ef2a4f3b28bf12df241cfaba733a4e96549909b2a91ff774da71c0e5c1bc4da4"

[[files]]
file = "config/friendlyfire.json"
hash = "2674bbc45aa053bc85e6f51e0f29726781f824806499cee992da43dc2ac2800f"

[[files]]
file = "config/immersive_optimization.json"
hash = "d6b21af8f75df1c3d4ad5e2e284d6cd6aca60b9338184ce63a477e14f9f6926c"

[[files]]
file = "config/immersive_paintings.json"
hash = "cc09b1ccc94ba0026b8c28c2055e59a263194ce21f447250048c36b82a1e6efd"

[[files]]
file = "config/logprot.json"
hash = "bd790367512f42f581f12f42213afa80d3eb6f6f90682089adbf5a3c6a8724f2"

[[files]]
file = "config/maidensmerrymaking-common.toml"
hash = "63232769007867c6145f65f830457a6337d49bce28fac4aec837ccc8ca532480"

[[files]]
file = "config/mmode.json"
hash = "50b1c63a3c790f273193d2b9011104517bb8987b3b4c513fc5a31ed14445034b"

[[files]]
file = "config/quark-common.toml"
hash = "b8705a396a93a8127a571739ed5e047d86911a6a24871eb84240841e313b4467"

[[files]]
file = "config/setworldspawnpoint.json5"
hash = "b2e2c7176c225f7c99f7c1f509c9f35b42ed87ce294a41fa0b05de21b47adf7d"

[[files]]
file = "config/simple-discord-link/embeds/default.json"
hash = "402b5180a4542d1bd327963cec3c6ff6778751488da8fc56246685df235e1936"

[[files]]
file = "config/simple-discord-link/language/en_us.json"
hash = "1f52e059d62cb835c6166f688d5638cc8265ccb0d6cb6b331074077aa6aa368e"

[[files]]
file = "config/simple-discord-link/simple-discord-compat.toml"
hash = "b6b95b5f2068b7f8fb030b11e6e6c5ccc8782feadc8fe5c7740e0133ea0b34d4"

[[files]]
file = "config/simple-discord-link/simple-discord-link.toml"
hash = "6cb5c39e609222114caf840005620770d608f500542a8bcbdd343a9e26b47e5c"

[[files]]
file = "config/simplebackups-common.toml"
hash = "e1677888261eb15c559b10004ac1469580b4641e4e9e33d2bfcde54cc1e3c8e6"

[[files]]
file = "config/vivecraft-server-config.toml"
hash = "2af6b1b5b68f9e4d6ff9509c5f769f546b7a6dd8bcbb93a98234a0f346a2982f"

[[files]]
file = "config/voicechat/translations.properties"
hash = "b258a94a5ed60fbf93b66c452c3d6e36b044f630741f90e5b13852a4805b235e"

[[files]]
file = "config/voicechat/voicechat-server.properties"
hash = "61358e0c04ee23b818dff357299076787247a1708749da49352f6ef2a373cb67"

[[files]]
file = "config/waystones-common.toml"
hash = "2a04be7bea544e155a5c0e0e66e527cedc75a4932fb71ff3b89cafadad3c13c4"

[[files]]
file = "config/worldborder.json5"
hash = "1cb75ed9f4ed4ae2668b65fd7c8dc267febb9e87b64c88e276ad3b08a1de6fe5"

[[files]]
file = "dynmap/configuration.txt"
hash = "1126a68aaa3c8e42474472e1db6d4b6dbaea3ac29f213a00f34aaa48a94a0728"

[[files]]
file = "dynmap/worlds.txt"
hash = "1041814b38723600665008e0b2fc50306f203fb99b3ffac295dc0a5db58f2ec2"

[[files]]
file = "journeymap/server/5.10/journeymap.server.default.config"
hash = "7a3d0b595cb2de70ce0e561ab496fbd965d65cd3591cfaaac45e383f32d1d096"

[[files]]
file = "journeymap/server/5.10/journeymap.server.global.config"
hash = "55ef282fc70a85255b3635a01ca80294f1db5ac8b60765d07f94379546e16da1"

[[files]]
file = "journeymap/server/5.10/journeymap.server.minecraft~overworld.config"
hash = "11efcf955815e14938f5e8194c37dcc674b23104f24a4a35faa2815017bbfb7d"

[[files]]
file = "journeymap/server/5.10/journeymap.server.minecraft~the_end.config"
hash = "eeeb8f9ea8c538c8733185a55da1797675b89ad74139c2983a97f2d8f53a35e5"

[[files]]
file = "journeymap/server/5.10/journeymap.server.minecraft~the_nether.config"
hash = "1cafa0682369923ceda5fa1264574510f8b35b4e703851746aec993005c886e4"

[[files]]
file = "maintenance.png"
hash = "5c2e1fe193220f54fb21e8c2a1dd56fd08e9ceee4aef4061a9ce0905f45516d5"

[[files]]
file = "mods/additional-redstone.pw.toml"
hash = "1847511b79dda27ac4483b3fbb9dd2a27d08ad177d3910ee70875c54f194c8d9"
metafile = true

[[files]]
file = "mods/alexs-mobs.pw.toml"
hash = "5e1239fd67c97c042d09cf38664698c9d1a3cfbc50d779fc550c461cf6aeb565"
metafile = true

[[files]]
file = "mods/alltheleaks.pw.toml"
hash = "40bab1828ae2b4d755db64f1c887a2fe06171fad6ab54d4a1863ca5c30ff9b55"
metafile = true

[[files]]
file = "mods/almanac-lib.pw.toml"
hash = "067c72c78318b03c01b6d35aff74135ef1c969425e471efe777dce7a174c7005"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
hash = "5e9edd1fd2395f14a0c8a4acbdbdd61e1047be1f0033deb3140d2ce0d093e9d8"
metafile = true

[[files]]
file = "mods/backpacked.pw.toml"
hash = "231924ea496fbdbf6f0b11af96a72ee1fb8cc5bd96d7d7e22eccd286d027bac0"
metafile = true

[[files]]
file = "mods/balm.pw.toml"
hash = "f8b6ef08945410e1341212a2723477487fb66a2c8fd67dd201433658791d298d"
metafile = true

[[files]]
file = "mods/better-compatibility-checker.pw.toml"
hash = "a167c88b43b73530c14b77d8cfa8c3546ee665ffa317f0451a6767e46bdae0de"
metafile = true

[[files]]
file = "mods/blueprint.pw.toml"
hash = "790de162313fcbe950496580db107eb8da2ae29060cbf611764d1bb352461d03"
metafile = true

[[files]]
file = "mods/bookshelf.pw.toml"
hash = "058699e4832d0cf5396c5ea29244100f0c0e39a8d7aa5b64c2afdcc3cb8c8145"
metafile = true

[[files]]
file = "mods/chisels-bits.pw.toml"
hash = "aca009f78e1223d44ba4b9683537d7acdd899b30834e25ab04a3092156725bcf"
metafile = true

[[files]]
file = "mods/chunky-pregenerator-forge.pw.toml"
hash = "7d3fded0a343b2953e2a77fd1d2ed7abc547d7008f5b1b842546f28b8df1b802"
metafile = true

[[files]]
file = "mods/citadel.pw.toml"
hash = "0c8838dba7d2090968ca9ec633260d42ca16f1df186a780bd5965994541d9f74"
metafile = true

[[files]]
file = "mods/collective.pw.toml"
hash = "492359a6ce93fbf09eb6e1d20b761a5538fe9197e7d129949234d83b87e06bc1"
metafile = true

[[files]]
file = "mods/coroutil.pw.toml"
hash = "9f2bb57e05bad305f03c25c275c6d11e952835a41b2da68dba10a0bd1f3f6261"
metafile = true

[[files]]
file = "mods/crafttweaker.pw.toml"
hash = "c986ab44a5f021f16ccdc9e100f77a146b1182918f6f01b12a5c672a2203d6a4"
metafile = true

[[files]]
file = "mods/craterlib.pw.toml"
hash = "10a8aac6b2aeb478bb663f2ddaa719ef32289676fdbe3251632ea2c6ce2bb578"
metafile = true

[[files]]
file = "mods/creativecore.pw.toml"
hash = "1a0099366159fe4c62c19e82b512375eaa528574cf1a7d60fc7b2c96e8a83a51"
metafile = true

[[files]]
file = "mods/cupboard.pw.toml"
hash = "2eb26b157c4159bfeff6a00147afa35284397d558f84b55367d1a41064d7456a"
metafile = true

[[files]]
file = "mods/curios.pw.toml"
hash = "1315cd56b0b4a5b3d53374cebf4f1f3cd0546b05058740847bd226c1d1ccab39"
metafile = true

[[files]]
file = "mods/dimension-access-manager.pw.toml"
hash = "952a9c5120f87a850ed26527cbfa1108d9ddd0fab8e2986f84082f0a3e041520"
metafile = true

[[files]]
file = "mods/display-delight.pw.toml"
hash = "fc6ca89075fc760ad49489b82248391a812965cde718239c12e02c46e3799c17"
metafile = true

[[files]]
file = "mods/dynmapforge.pw.toml"
hash = "a9df7957db29bd5934360117797e75baa6fc0a12a9ef99c1bddb66a7ad30a7ce"
metafile = true

[[files]]
file = "mods/emojiful.pw.toml"
hash = "3b8dacbd1cd0e3d849b080473559fd26e4268e396075ad37d0fdf7031ee9dc97"
metafile = true

[[files]]
file = "mods/farmers-delight.pw.toml"
hash = "067fc433511066d18b1795b86c9856246a8da7f9a4316afd6b25e5eee181f660"
metafile = true

[[files]]
file = "mods/fast-leaf-decay.pw.toml"
hash = "fd5aa059dd7e148e9ce801455b438425c0ad36537ce4b635edeb524900b15284"
metafile = true

[[files]]
file = "mods/ferritecore.pw.toml"
hash = "5bd0506bc0be25116b234f2b5af9447f60d82ae1cb6c5be4e12d8841f6c2501c"
metafile = true

[[files]]
file = "mods/framework.pw.toml"
hash = "376f8a190f00bd120193d7a665ebe1b03dfe329cc395f7d944f7216c1182c84d"
metafile = true

[[files]]
file = "mods/friendly-fire.pw.toml"
hash = "905aa52f559261f30b07aadb82e18c9cf12981b91b1213b52d87d57d9772edef"
metafile = true

[[files]]
file = "mods/ftb-essentials.pw.toml"
hash = "8cf91dcad4590fed49069cdae47b211bdbee7da6e0c175ae802421ec6a961ae1"
metafile = true

[[files]]
file = "mods/ftb-library-forge.pw.toml"
hash = "48e2fa3089beed20a23ff2d171259768b2080ab0ff196841a18eb93c38e1c8b2"
metafile = true

[[files]]
file = "mods/ftb-ranks-forge.pw.toml"
hash = "9142dedf3cfa73a62277eee9922561b1576976ecb4521059c4db4b8994f9f5e5"
metafile = true

[[files]]
file = "mods/geckolib.pw.toml"
hash = "88f142bda6bfa6aff4f4d4e12b8ba7581aa40e3f163039a533f09dd6d634e093"
metafile = true

[[files]]
file = "mods/gravestone-mod.pw.toml"
hash = "b55f3276124e13e8b3899d4d0400e990dea41d228644be34b341e62fe8abed6e"
metafile = true

[[files]]
file = "mods/hourglass.pw.toml"
hash = "fbb371c2bb573d6d84600f10937f535b7f19f7df6e536f25b7b4e46471c32904"
metafile = true

[[files]]
file = "mods/immersive-optimization.pw.toml"
hash = "ed4a5d39c2cb8a41d49f7e118ceb43a04f7984d6cbd706389b7d736c507bf00a"
metafile = true

[[files]]
file = "mods/immersive-paintings.pw.toml"
hash = "c006beeec7fca82263506ab1fda78e472e54bb64be350e130902f4f475df25cb"
metafile = true

[[files]]
file = "mods/jade-addons.pw.toml"
hash = "140a929fda55621de5a03378f7478f587e0a1e912a3e46815fa7305070d2c71c"
metafile = true

[[files]]
file = "mods/jade.pw.toml"
hash = "8f359d190506a6f824763b8e7c390d9e22204ef11e3ffa5ef980000d17e2c2b6"
metafile = true

[[files]]
file = "mods/jei.pw.toml"
hash = "94a0ed0630ad6e53af1e317e86a195672f4627552fde677396ac94eefce6ffc6"
metafile = true

[[files]]
file = "mods/journeymap.pw.toml"
hash = "664a573384edf644e9b788c7c29fe32593917ac8283bb794cc46b471a0a6504a"
metafile = true

[[files]]
file = "mods/krypton-reforged.pw.toml"
hash = "ba2f214504381c53f588e1a52d8be657b47ed53a256b45d623cea2c724748afa"
metafile = true

[[files]]
file = "mods/let-me-despawn.pw.toml"
hash = "644607a28024fbb4115884962a09cb4621217f652aacd363f7a2df52ddb69862"
metafile = true

[[files]]
file = "mods/lithostitched.pw.toml"
hash = "1d623ba29fcb52d5db733af383a13273792ac3dc1ac7a8f9e3f58a17ae1bc2c7"
metafile = true

[[files]]
file = "mods/login-protection.pw.toml"
hash = "0a96e881040a95b2543d18afc3f9e1727e64659ec1548ed2df4fcd7dafbfbbc7"
metafile = true

[[files]]
file = "mods/lootr.pw.toml"
hash = "e8b4876d403b4f4daab64bad9704a5b271a33031d1ff8d19d23ebd1e3b8dd39a"
metafile = true

[[files]]
file = "mods/macaws-bridges.pw.toml"
hash = "48b6be3ef711114f233e0c36d7f625b1e42c247c3e78a51fd7498886657a2384"
metafile = true

[[files]]
file = "mods/macaws-doors.pw.toml"
hash = "33af5f73cc7b802cf45b02ef7ec7b9a516919d55ed32a035a4661f33331b5531"
metafile = true

[[files]]
file = "mods/macaws-furniture.pw.toml"
hash = "3706f6817a641198fc325d578d189d502af7c3444148a72e4dc23f214c3611a1"
metafile = true

[[files]]
file = "mods/macaws-lights-and-lamps.pw.toml"
hash = "9662a11bbab322c2c29d84bf88d0a6c11e3dbfc2e996a484fa1a1ef2f91a18ad"
metafile = true

[[files]]
file = "mods/macaws-paths-and-pavings.pw.toml"
hash = "e1b4f834c2a9bbcc9ea812fc0658e62b0696b8f77dc2f6ab54568d7b8059b2a5"
metafile = true

[[files]]
file = "mods/macaws-roofs.pw.toml"
hash = "6445161fb93a765e776f97573a32af44d0615133b76f33d56da1b842eb5fc377"
metafile = true

[[files]]
file = "mods/macaws-stairs.pw.toml"
hash = "9906e6412e0dbce8a80dad82699d576f95c04cc4574e636705d9ac3e6686b0a2"
metafile = true

[[files]]
file = "mods/macaws-windows.pw.toml"
hash = "8ee3776430187fb4d69278e645e10fefb7fe7342caee0a5861479ce25956713a"
metafile = true

[[files]]
file = "mods/maidens-merry-making.pw.toml"
hash = "da744a0327fd701293da78d745c41907c6a8096086935a134a1edefa590b39a4"
metafile = true

[[files]]
file = "mods/maintenance-mode-forge-fabric-quilt.pw.toml"
hash = "421ae73f3d143681f4b527256020513f021e37616ff6eb1aa731ae2ad7f6842a"
metafile = true

[[files]]
file = "mods/mobtimizations.pw.toml"
hash = "1623bcd1af853d7e4490c4c689668dea6c6bc238d5bb90c5c1113fa9f6cd1b5c"
metafile = true

[[files]]
file = "mods/modernfix.pw.toml"
hash = "11cd7da81a933aab04f091e2c25447b6d11ebe98bfeed244426a86dd31f3df04"
metafile = true

[[files]]
file = "mods/netherportalfix.pw.toml"
hash = "820d6b97344411476b96ae2bc8a3e4b9e30e15dfd15d8d0c945726b0011928d4"
metafile = true

[[files]]
file = "mods/noisium.pw.toml"
hash = "dbd8ee9c150f054d96e1e3cf97c8cb169cf854a84532e21daab9e11309a67fcf"
metafile = true

[[files]]
file = "mods/patchouli.pw.toml"
hash = "dec2bc011d4ca1d451aaa3eea477f13366bfb13beba0716018f47d9331a50d8e"
metafile = true

[[files]]
file = "mods/pet-cemetery.pw.toml"
hash = "baa01dee313f30743a8306dea4253e52975c2f36f04d9dbc9f982ad1686e9937"
metafile = true

[[files]]
file = "mods/pet-transfer-trade-your-pets.pw.toml"
hash = "2aa055a2c6290b4e315ef300a62a0e0191a48fa0d26133defca071c812a1b150"
metafile = true

[[files]]
file = "mods/quark.pw.toml"
hash = "4eb683644ee4e38e00b06df946b71ad8fedaa860fcabbd91ec6ceb71c65b8d81"
metafile = true

[[files]]
file = "mods/radium-reforged.pw.toml"
hash = "77fa86d36ada0d178545853f987f9e71128e1833c9c29ae62c436c09bdb31948"
metafile = true

[[files]]
file = "mods/railcraft-reborn.pw.toml"
hash = "97395fda39964adaead0825c20f48b0e5f211b709cb78d16e3f7477a39398a56"
metafile = true

[[files]]
file = "mods/serializationisbad.pw.toml"
hash = "3ecec65e3a2ff50bfe96ba232533ac8117c3644903d0a01d5783c8f0f4baad45"
metafile = true

[[files]]
file = "mods/set-world-spawn-point.pw.toml"
hash = "ac37246c59330db7b0fd4a334ff233cf493c6bd6745571ac9fed5514d796f1cc"
metafile = true

[[files]]
file = "mods/signpost.pw.toml"
hash = "33d1f8465340427f98582f96361f44cd9c1f17b292fe0dd418fc08b78e677003"
metafile = true

[[files]]
file = "mods/simple-backups.pw.toml"
hash = "befdd7852cd8a3c5517e6c42ec706f22a1c60888f603cd338584f891e817be6b"
metafile = true

[[files]]
file = "mods/simple-discord-link-bot-forge-fabric-spigot.pw.toml"
hash = "9b8835befc435ad8bf636915ca93a90397e1e3b8cbdcae6641f24bb5b36187a2"
metafile = true

[[files]]
file = "mods/simple-shops.pw.toml"
hash = "eb50118ab1d53243ffec8d8ec8ffac84e046232e09feb2c5a4597542fc9f4671"
metafile = true

[[files]]
file = "mods/simple-voice-chat.pw.toml"
hash = "6a48a6cb7442b8f045673d6de3e3590ae8252e66ea8c6f11f69f1d45b2304043"
metafile = true

[[files]]
file = "mods/small-ships.pw.toml"
hash = "a2641c9187ec8485df45b2fb25c901f835da50ffe4d9601e4ecc81fc9036eb55"
metafile = true

[[files]]
file = "mods/smooth-chunk-save.pw.toml"
hash = "a061b4f98461fc38b4ff6495b5e3a9b8708e9d87333c2cbb29e6b265053a5abe"
metafile = true

[[files]]
file = "mods/spark.pw.toml"
hash = "d0e1a79dbcda8499e0f12f4adaa5503f9bbc84a6274ce07b3a3839476622e8e5"
metafile = true

[[files]]
file = "mods/tectonic.pw.toml"
hash = "a01449c29314bff0ad2047911d8253641801e01997709f53fa5b3f52954232a3"
metafile = true

[[files]]
file = "mods/vivecraft.pw.toml"
hash = "e906ca5adfdceeaaa1beb6d04e554e7b874979bd596e699dba3e30d3e8125c5c"
metafile = true

[[files]]
file = "mods/waterframes.pw.toml"
hash = "f23d71ce94d45ce3c219c66196680081cd445ed28048f9a9a8217c52669644b2"
metafile = true

[[files]]
file = "mods/waystones.pw.toml"
hash = "5dbc1ed70c1dd5c99c93d353b6267c6a4e7af2b342d0ad4ddecf54593e199224"
metafile = true

[[files]]
file = "mods/world-border.pw.toml"
hash = "a303192d78ce87e6249c6ef4090c2d706b8bbbe0440a55b7d7bdc61db195370a"
metafile = true

[[files]]
file = "mods/worldedit.pw.toml"
hash = "bd1dc13316e2aa9b56c89e7e974057f8da8d6bbfe707ba4210109fc612b782e3"
metafile = true

[[files]]
file = "mods/zeta.pw.toml"
hash = "557d160e4a3d856c6bbe36c39ee7c6cd42824363690b61d5f23bbac153c8edbc"
metafile = true

[[files]]
file = "scripts/railcraft.zs"
hash = "dd53340039583f2820d3b0fb785bb4671ba3b3f95643c052884778d9f9061b79"

[[files]]
file = "world/datapacks/anti creeper grief v1.1.7 (MC 1.20-1.20.6).zip"
hash = "c6edcc0bafd1ea1acf11193f4a1613f701b17192b85886652ba6699125f91976"

[[files]]
file = "world/datapacks/anti enderman grief v1.1.7 (MC 1.20-1.20.6).zip"
hash = "b637f7394e4e4931194e1b6872ffb5486f7ae8854c61b492468452c26b91ff91"

[[files]]
file = "world/datapacks/bat membranes v1.0.9 (MC 1.20-1.20.6).zip"
hash = "db8d2ce49948ba542b7ff3435a6c2c9741ad9c513a4e9e4144807fd866086c40"

[[files]]
file = "world/serverconfig/dimension_access_manager-server.toml"
hash = "f0a0bc057bde4fca9649484b281eaeafcb602770c6488c93fc4c1244ceab0f1e"

[[files]]
file = "world/serverconfig/ftbessentials.snbt"
hash = "8172f1e5efbdb00cff632bc2d36b3d30cbc4f3ef5b6c0f5a1c165b60b8e2f0dd"

[[files]]
file = "world/serverconfig/ftbranks/ranks.snbt"
hash = "0fe74ee3b51ef1712ca19cf1cbc22affc908831db24def25b48e54f246fb226e"

[[files]]
file = "world/serverconfig/gravestone-server.toml"
hash = "8e13311da9b8861ab596080c57ebe48eedfb9d45a28817d7e2af4d5f9aff241b"

[[files]]
file = "world/serverconfig/hourglass-server.toml"
hash = "0b1aede18f0f305fbc221602af919ba84eccbd7278131789ec997a1f4f89676f"

[[files]]
file = "world/serverconfig/journeymap-server.toml"
hash = "cb9df9debbc04baab5ad473f10049b67887b96404c7997983d26c9a98d2c102a"

[[files]]
file = "world/serverconfig/railcraft-server.toml"
hash = "2cd236244ae9ea9eee684608c4ac993b3429807e275ca1f8927974a0166855aa"

[[files]]
file = "world/serverconfig/signpost-server.toml"
hash = "9f071e74c45f9231ae51bfc967bbdc2668e468b05079aa7e52c76281f74441f6"

[[files]]
file = "world/serverconfig/waterframes-server.toml"
hash = "3102be29d8ad68758338adf301220cae7ccd44dac7ab7f5db4dd462e115fe00a"
