name = "CweamCraft"
author = "CPU_Blanc"
version = "1.3.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e6e9af9795268d17db12c22b03f7dff668728cd5413aabb3dfbba7b7cff703f0"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
