name = "CweamCraft"
author = "CPU_Blanc"
version = "1.3.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "48cb83f4d51873a97fb223fe3e58a37a81dcabd0d5cd5f4435a05d897940fddb"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
