name = "CweamCraft"
author = "CPU_Blanc"
version = "1.3.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "82b3b8ff3135dd35810c9ec1c4db626b6f093a1c4a3be0a07d0f3c33c1f80133"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
