name = "CweamCraft"
author = "CPU_Blanc"
version = "1.3.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5c31f52739f2d8f30b95746132e65118537c856b2c6f3f37ec8731afa436f8ce"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
