hash-format = "sha256"

[[files]]
file = "config/DistantHorizons.toml"
hash = "eb44ddf3d44d9f182a12d86046eb7d12bedb223103fa2e320e27db009a63cb71"

[[files]]
file = "config/bcc-common.toml"
hash = "d41e36fbca9e8c6b1ce9a45408f0191d731d69bce2b7f80e480ca8517fa18b75"

[[files]]
file = "config/defaultoptions/keybindings.txt"
hash = "29e7cb04bc4f7dcf70e5352182bff7bd064ac604bf354d5b89de56dd55c38be9"

[[files]]
file = "config/defaultoptions/options.txt"
hash = "70f3b9ec75fa80440cf482d7f3f5a448f66acbe4b0b76818cd5f9014408aa12c"

[[files]]
file = "config/defaultoptions/servers.dat"
hash = "d85bc6ba4c3bb870ec48d94c71cdc4629382724fb22bd1f6c7d890cab89c5d8b"

[[files]]
file = "config/emojiful-client.toml"
hash = "d1475ba8120de5c3d68cb93d3751a54811b16a22833421f6b6d548b67028803c"

[[files]]
file = "config/inventoryprofilesnext/inventoryprofiles.json"
hash = "d6ef3d7a5517c89721d70bb8c73b9f5e0c988b28001b3a4b0fe41f5335c66548"

[[files]]
file = "config/quark-common.toml"
hash = "110a879d5c49317efd5d64c153c93ff6016f9c08e61335df981e1cbb5bd79c64"

[[files]]
file = "journeymap/config/5.10/journeymap.core.config"
hash = "71709b74727d4fe97940e4e23950ad062046a49435cdff87f391c6bfb8d9bea4"

[[files]]
file = "journeymap/config/5.10/journeymap.fullmap.config"
hash = "201563a051ab6ae8767d10ed4edd20a2ab5269aa13bccfac83bb6b09dee45305"

[[files]]
file = "journeymap/config/5.10/journeymap.minimap.config"
hash = "57805d53b705df64baaa12f8c60bb44c1da9c91ac00721215fb4a74b1a8b8158"

[[files]]
file = "journeymap/config/5.10/journeymap.minimap2.config"
hash = "c50f32cb505264a23fddf2b5020df421e3f68e5fe68975873e9e6ea3cff58349"

[[files]]
file = "journeymap/config/5.10/journeymap.topo.config"
hash = "9e273064e62c540e09d104258a8ea0d88e8dd9e2c2e22605b243f92f33f39847"

[[files]]
file = "journeymap/config/5.10/journeymap.waypoint.config"
hash = "ef311d5f27219bd7fb76a2c794ae8523efa3b953328455974cc5625121ab0467"

[[files]]
file = "journeymap/config/5.10/journeymap.webmap.config"
hash = "629ff218d4305e5262d0eff38ca2261f2033dda46c8e9f8c0d5815bfcf52bd77"

[[files]]
file = "mods/additional-redstone.pw.toml"
hash = "1847511b79dda27ac4483b3fbb9dd2a27d08ad177d3910ee70875c54f194c8d9"
metafile = true

[[files]]
file = "mods/alexs-mobs.pw.toml"
hash = "5e1239fd67c97c042d09cf38664698c9d1a3cfbc50d779fc550c461cf6aeb565"
metafile = true

[[files]]
file = "mods/alltheleaks.pw.toml"
hash = "40bab1828ae2b4d755db64f1c887a2fe06171fad6ab54d4a1863ca5c30ff9b55"
metafile = true

[[files]]
file = "mods/backpacked.pw.toml"
hash = "231924ea496fbdbf6f0b11af96a72ee1fb8cc5bd96d7d7e22eccd286d027bac0"
metafile = true

[[files]]
file = "mods/balm.pw.toml"
hash = "f8b6ef08945410e1341212a2723477487fb66a2c8fd67dd201433658791d298d"
metafile = true

[[files]]
file = "mods/better-compatibility-checker.pw.toml"
hash = "a167c88b43b73530c14b77d8cfa8c3546ee665ffa317f0451a6767e46bdae0de"
metafile = true

[[files]]
file = "mods/blueprint.pw.toml"
hash = "790de162313fcbe950496580db107eb8da2ae29060cbf611764d1bb352461d03"
metafile = true

[[files]]
file = "mods/bookshelf.pw.toml"
hash = "058699e4832d0cf5396c5ea29244100f0c0e39a8d7aa5b64c2afdcc3cb8c8145"
metafile = true

[[files]]
file = "mods/chisels-bits.pw.toml"
hash = "aca009f78e1223d44ba4b9683537d7acdd899b30834e25ab04a3092156725bcf"
metafile = true

[[files]]
file = "mods/citadel.pw.toml"
hash = "0c8838dba7d2090968ca9ec633260d42ca16f1df186a780bd5965994541d9f74"
metafile = true

[[files]]
file = "mods/configured.pw.toml"
hash = "c1bdeff356cd2ac164e2c0e6d0ceeda234db9774c2df44fb9f0e71d3960cc3f1"
metafile = true

[[files]]
file = "mods/controlling.pw.toml"
hash = "1e56f528d8e21b0cf9c52c3d6deea2a4eafa408170b39a070195dbf66617f373"
metafile = true

[[files]]
file = "mods/crafttweaker.pw.toml"
hash = "c986ab44a5f021f16ccdc9e100f77a146b1182918f6f01b12a5c672a2203d6a4"
metafile = true

[[files]]
file = "mods/creativecore.pw.toml"
hash = "1a0099366159fe4c62c19e82b512375eaa528574cf1a7d60fc7b2c96e8a83a51"
metafile = true

[[files]]
file = "mods/culllessleaves-reforged.pw.toml"
hash = "e38d187eefae043e892eb6ce932f5360718d02d71f9e8072e8ec38ec0667753b"
metafile = true

[[files]]
file = "mods/curios.pw.toml"
hash = "1315cd56b0b4a5b3d53374cebf4f1f3cd0546b05058740847bd226c1d1ccab39"
metafile = true

[[files]]
file = "mods/default-options.pw.toml"
hash = "91e64b2bf3b7011473fc138e5e93686233622fb0188bbf1d1113abadac5e42d7"
metafile = true

[[files]]
file = "mods/dimension-access-manager.pw.toml"
hash = "952a9c5120f87a850ed26527cbfa1108d9ddd0fab8e2986f84082f0a3e041520"
metafile = true

[[files]]
file = "mods/display-delight.pw.toml"
hash = "fc6ca89075fc760ad49489b82248391a812965cde718239c12e02c46e3799c17"
metafile = true

[[files]]
file = "mods/distant-horizons.pw.toml"
hash = "8ca9e5b3e963b96bc66a03a35361184e9ea42194902a6968b76de36f8e1116a9"
metafile = true

[[files]]
file = "mods/ebe-forge.pw.toml"
hash = "54c84727c0d0423a3d7f0049bd3b1b7d9136ff1f41ce5fc83d6c29c6119ea4b0"
metafile = true

[[files]]
file = "mods/embeddium.pw.toml"
hash = "a1575677daaaf6ea6dac12e5a10073e34025e5ca2c35b6d36ad4a5a0edbc0e82"
metafile = true

[[files]]
file = "mods/emojiful.pw.toml"
hash = "3b8dacbd1cd0e3d849b080473559fd26e4268e396075ad37d0fdf7031ee9dc97"
metafile = true

[[files]]
file = "mods/farmers-delight.pw.toml"
hash = "067fc433511066d18b1795b86c9856246a8da7f9a4316afd6b25e5eee181f660"
metafile = true

[[files]]
file = "mods/ferritecore.pw.toml"
hash = "5bd0506bc0be25116b234f2b5af9447f60d82ae1cb6c5be4e12d8841f6c2501c"
metafile = true

[[files]]
file = "mods/framework.pw.toml"
hash = "376f8a190f00bd120193d7a665ebe1b03dfe329cc395f7d944f7216c1182c84d"
metafile = true

[[files]]
file = "mods/friendly-fire.pw.toml"
hash = "905aa52f559261f30b07aadb82e18c9cf12981b91b1213b52d87d57d9772edef"
metafile = true

[[files]]
file = "mods/geckolib.pw.toml"
hash = "88f142bda6bfa6aff4f4d4e12b8ba7581aa40e3f163039a533f09dd6d634e093"
metafile = true

[[files]]
file = "mods/gravestone-mod.pw.toml"
hash = "b55f3276124e13e8b3899d4d0400e990dea41d228644be34b341e62fe8abed6e"
metafile = true

[[files]]
file = "mods/hourglass.pw.toml"
hash = "fbb371c2bb573d6d84600f10937f535b7f19f7df6e536f25b7b4e46471c32904"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "eb089373d47632a85bb7596b1143b719d7675f5e2782586aa0c340069d699700"
metafile = true

[[files]]
file = "mods/immersive-paintings.pw.toml"
hash = "c006beeec7fca82263506ab1fda78e472e54bb64be350e130902f4f475df25cb"
metafile = true

[[files]]
file = "mods/inventory-profiles-next.pw.toml"
hash = "fb8b143630e9d758531fa727594c76b8735f1c7a8ecc4911307c8e71e99b70a1"
metafile = true

[[files]]
file = "mods/jade-addons.pw.toml"
hash = "140a929fda55621de5a03378f7478f587e0a1e912a3e46815fa7305070d2c71c"
metafile = true

[[files]]
file = "mods/jade.pw.toml"
hash = "8f359d190506a6f824763b8e7c390d9e22204ef11e3ffa5ef980000d17e2c2b6"
metafile = true

[[files]]
file = "mods/jei.pw.toml"
hash = "94a0ed0630ad6e53af1e317e86a195672f4627552fde677396ac94eefce6ffc6"
metafile = true

[[files]]
file = "mods/journeymap.pw.toml"
hash = "664a573384edf644e9b788c7c29fe32593917ac8283bb794cc46b471a0a6504a"
metafile = true

[[files]]
file = "mods/kotlin-for-forge.pw.toml"
hash = "1678327ac50408273c1828b631929128d3fdfd54cda7b2e823ce9352495a68ff"
metafile = true

[[files]]
file = "mods/krypton-reforged.pw.toml"
hash = "ba2f214504381c53f588e1a52d8be657b47ed53a256b45d623cea2c724748afa"
metafile = true

[[files]]
file = "mods/libipn.pw.toml"
hash = "ee79f551b7aede4b923fc6df137c4ebbb1dd21eb80a3aaba6da8be93ac5010e7"
metafile = true

[[files]]
file = "mods/lighty.pw.toml"
hash = "fbbc480f1deb4e8474a917e9c2ef7806c00ae90e51d04d03780a3bc50281fbca"
metafile = true

[[files]]
file = "mods/lithostitched.pw.toml"
hash = "1d623ba29fcb52d5db733af383a13273792ac3dc1ac7a8f9e3f58a17ae1bc2c7"
metafile = true

[[files]]
file = "mods/lootr.pw.toml"
hash = "e8b4876d403b4f4daab64bad9704a5b271a33031d1ff8d19d23ebd1e3b8dd39a"
metafile = true

[[files]]
file = "mods/macaws-bridges.pw.toml"
hash = "48b6be3ef711114f233e0c36d7f625b1e42c247c3e78a51fd7498886657a2384"
metafile = true

[[files]]
file = "mods/macaws-doors.pw.toml"
hash = "33af5f73cc7b802cf45b02ef7ec7b9a516919d55ed32a035a4661f33331b5531"
metafile = true

[[files]]
file = "mods/macaws-furniture.pw.toml"
hash = "3706f6817a641198fc325d578d189d502af7c3444148a72e4dc23f214c3611a1"
metafile = true

[[files]]
file = "mods/macaws-lights-and-lamps.pw.toml"
hash = "9662a11bbab322c2c29d84bf88d0a6c11e3dbfc2e996a484fa1a1ef2f91a18ad"
metafile = true

[[files]]
file = "mods/macaws-paths-and-pavings.pw.toml"
hash = "e1b4f834c2a9bbcc9ea812fc0658e62b0696b8f77dc2f6ab54568d7b8059b2a5"
metafile = true

[[files]]
file = "mods/macaws-roofs.pw.toml"
hash = "6445161fb93a765e776f97573a32af44d0615133b76f33d56da1b842eb5fc377"
metafile = true

[[files]]
file = "mods/macaws-stairs.pw.toml"
hash = "9906e6412e0dbce8a80dad82699d576f95c04cc4574e636705d9ac3e6686b0a2"
metafile = true

[[files]]
file = "mods/macaws-windows.pw.toml"
hash = "8ee3776430187fb4d69278e645e10fefb7fe7342caee0a5861479ce25956713a"
metafile = true

[[files]]
file = "mods/maidens-merry-making.pw.toml"
hash = "da744a0327fd701293da78d745c41907c6a8096086935a134a1edefa590b39a4"
metafile = true

[[files]]
file = "mods/modernfix.pw.toml"
hash = "11cd7da81a933aab04f091e2c25447b6d11ebe98bfeed244426a86dd31f3df04"
metafile = true

[[files]]
file = "mods/oculus.pw.toml"
hash = "5ef885f9912ff6aa73db254b63a3cd22520f06261bc3c38e7c92f449806a9044"
metafile = true

[[files]]
file = "mods/patchouli.pw.toml"
hash = "dec2bc011d4ca1d451aaa3eea477f13366bfb13beba0716018f47d9331a50d8e"
metafile = true

[[files]]
file = "mods/pet-cemetery.pw.toml"
hash = "baa01dee313f30743a8306dea4253e52975c2f36f04d9dbc9f982ad1686e9937"
metafile = true

[[files]]
file = "mods/pet-transfer-trade-your-pets.pw.toml"
hash = "2aa055a2c6290b4e315ef300a62a0e0191a48fa0d26133defca071c812a1b150"
metafile = true

[[files]]
file = "mods/quark.pw.toml"
hash = "4eb683644ee4e38e00b06df946b71ad8fedaa860fcabbd91ec6ceb71c65b8d81"
metafile = true

[[files]]
file = "mods/radium-reforged.pw.toml"
hash = "77fa86d36ada0d178545853f987f9e71128e1833c9c29ae62c436c09bdb31948"
metafile = true

[[files]]
file = "mods/railcraft-reborn.pw.toml"
hash = "97395fda39964adaead0825c20f48b0e5f211b709cb78d16e3f7477a39398a56"
metafile = true

[[files]]
file = "mods/searchables.pw.toml"
hash = "2cb8dd9a3944a6430b49916a4fe1b6cf0bd7efd907054f8e679a02717149404f"
metafile = true

[[files]]
file = "mods/signpost.pw.toml"
hash = "33d1f8465340427f98582f96361f44cd9c1f17b292fe0dd418fc08b78e677003"
metafile = true

[[files]]
file = "mods/simple-shops.pw.toml"
hash = "eb50118ab1d53243ffec8d8ec8ffac84e046232e09feb2c5a4597542fc9f4671"
metafile = true

[[files]]
file = "mods/simple-voice-chat.pw.toml"
hash = "6a48a6cb7442b8f045673d6de3e3590ae8252e66ea8c6f11f69f1d45b2304043"
metafile = true

[[files]]
file = "mods/skin-layers-3d.pw.toml"
hash = "96faed6998f9d3d7240f35111b9793370b83e6c4f984545fa228f799398595eb"
metafile = true

[[files]]
file = "mods/small-ships.pw.toml"
hash = "a2641c9187ec8485df45b2fb25c901f835da50ffe4d9601e4ecc81fc9036eb55"
metafile = true

[[files]]
file = "mods/sound-physics-remastered.pw.toml"
hash = "ee2d9154be68ef20293596a3f65810111fd35a802f1e8292e9ba8872de463a14"
metafile = true

[[files]]
file = "mods/tectonic.pw.toml"
hash = "a01449c29314bff0ad2047911d8253641801e01997709f53fa5b3f52954232a3"
metafile = true

[[files]]
file = "mods/toadlib.pw.toml"
hash = "5c581033ed8e02c6e2c3c35e721f45e8ce865e5c8216c86696bad17ce57cbe57"
metafile = true

[[files]]
file = "mods/vivecraft.pw.toml"
hash = "e906ca5adfdceeaaa1beb6d04e554e7b874979bd596e699dba3e30d3e8125c5c"
metafile = true

[[files]]
file = "mods/waterframes.pw.toml"
hash = "f23d71ce94d45ce3c219c66196680081cd445ed28048f9a9a8217c52669644b2"
metafile = true

[[files]]
file = "mods/watermedia-yt-plugin.pw.toml"
hash = "0a124d952a34781cc8b511bd56a7468b24e75c5a8d3510a016737525594965a7"
metafile = true

[[files]]
file = "mods/watermedia.pw.toml"
hash = "0528731743be7df4ba5a8952264861920f90475ed333f914fddea75473cd6012"
metafile = true

[[files]]
file = "mods/waystones.pw.toml"
hash = "5dbc1ed70c1dd5c99c93d353b6267c6a4e7af2b342d0ad4ddecf54593e199224"
metafile = true

[[files]]
file = "mods/zeta.pw.toml"
hash = "557d160e4a3d856c6bbe36c39ee7c6cd42824363690b61d5f23bbac153c8edbc"
metafile = true

[[files]]
file = "resourcepacks/faithful-32x.pw.toml"
hash = "353d439e094a067c199eb744d0a20b0f87cc8dcde937ddc3ee6bd0f183e29a6e"
metafile = true

[[files]]
file = "resourcepacks/soft-weather.pw.toml"
hash = "a76052f76e4eeb7f6114f3bad62fc1e967b8f39425bfb1e369c2ead7d56519b0"
metafile = true

[[files]]
file = "resourcepacks/stay-true.pw.toml"
hash = "84209283dcd07c0fcb4f14c5e579f443d6ff277e18e8b89c2b7dadee0febc41a"
metafile = true

[[files]]
file = "resourcepacks/§cWearable Christmas Hats§0_§8[v2]§0.zip"
hash = "926a04efa0179e35577f7deed7def144d7bafc20efa100f1919eff9247b235b9"

[[files]]
file = "shaderpacks/complementary-reimagined.pw.toml"
hash = "9f8e443df6075210eef82f35c5f95db92c19d7b1a1267a4593fa97c079993ed6"
metafile = true

[[files]]
file = "shaderpacks/photon-shader.pw.toml"
hash = "09c8e6752fe02ae348923b6038bc1c3d4b06f452886a1d42c90d72adcc2e40ef"
metafile = true
