name = "CweamCraft"
author = "CPU_Blanc"
version = "1.3.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9339881ff3b9ff7863c4a45af06e403b751388857696e9e8b72eae29b8db9408"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
