name = "CweamCraft"
author = "CPU_Blanc"
version = "1.3.1-xmas"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "66893d4f20ef219d1d8b6f810cd6981670ea4f3838b02c6a6f4ebf94387e416e"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
