name = "CweamCraft"
author = "CPU_Blanc"
version = "1.3.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4a3b7f78844da0c74e1d6fee009dde0227805cc91058428be543a4c82a292f7a"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
