name = "CweamCraft"
author = "CPU_Blanc"
version = "1.3.1-xmas"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b43000631c01b7dbd09d12317fc652ab5ae8767eb23e0288a09b2e93b5858450"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
