name = "CweamCraft"
author = "CPU_Blanc"
version = "1.3.1-xmas"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "eae3da44826b8bac541a7838ace7eb45bb28205a157d69b75197d17603ff0eeb"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
